# Generated by Django 3.2 on 2022-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='random_id',
            field=models.CharField(default=1321, max_length=10),
            preserve_default=False,
        ),
    ]
