# Generated by Django 3.2 on 2022-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_response_random_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
