# Generated by Django 3.2 on 2022-10-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_response_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
