# Generated by Django 3.2 on 2022-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(default='名無しさん', max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='コメント内容'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=100, verbose_name='スレッドタイトル'),
        ),
    ]
