# Generated by Django 3.2 on 2022-10-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20221025_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='code',
            new_name='delete_code',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='code',
            new_name='delete_code',
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
