# Generated by Django 3.2 on 2022-10-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20221026_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='delete_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
