# Generated by Django 3.2 on 2022-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_thread_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='delete_code',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='delete_code',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
