# Generated by Django 3.2 on 2022-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20221026_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='response',
            name='delete_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='削除用コード'),
        ),
    ]
