# Generated by Django 3.2 on 2022-10-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='updated_at',
        ),
    ]
