# Generated by Django 3.2 on 2022-10-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_key_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='delete_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='削除用コード'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='delete_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='削除用コード'),
        ),
    ]
